name: Python Package using Conda

on: [push]

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        activate-environment: leetcode-env
        python-version: 3.10
        auto-update-conda: true
        environment-file: environment.yml   # optional if you already have one
        channels: defaults

    - name: Lint with flake8
      run: |
        conda install -y flake8
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

    - name: Test with pytest
      run: |
        conda install -y pytest
        pytest
